import QtQuick 2.15
import QtQuick.Controls 2.15

Rectangle{
    width:parent.width
    height:parent.height
    color: "#777777"
    Rectangle{
        id:titleBox
        height:parent.height/20
        width:parent.width
        color:"#AAAAAA"
        Text{
            anchors.centerIn:parent
            text:"State Selector"
        }
    }
    Rectangle{
        height:parent.height-titleBox.height
        width:parent.width
        y:titleBox.height
        color:parent.color
            Rectangle{
                id:trackStateList
                height:parent.height
                width:parent.width/3
                color:parent.color
                Rectangle{
                    height:parent.height/20
                    width:parent.width
                    color:titleBox.color
                    Text{
                        anchors.centerIn:parent
                        text:"Pulls"
                    }
                }
                Rectangle{
                    height:parent.height-parent.height/20
                    width:parent.width
                    color:parent.color
                    y:parent.height/20
                ListView{
                    model: ListModel{
                        ListElement{name:"Running";value:1;box_color:"#00FF00"}
                        ListElement{name:"Reseting";value:2;box_color:"#FFFF00"}
                        ListElement{name:"Stopped";value:3;box_color:"#FF0000"}
                        ListElement{name:"Man/Dur";value:4;box_color:"#0000FF"}
                    }
                    spacing:parent.height/50
                    width:parent.width
                    height:parent.height
                    delegate:Rectangle{
                        color:box_color
                        width:trackStateList.width
                        height:trackStateList.width
                        radius:height/5
                        Text{
                            anchors.centerIn:parent
                            text:name
                        }
                        MouseArea{
                            anchors.fill:parent
                            onClicked:dataModel.set_pull_state(value)
                        }
                    }
                }
            }    
        }

        Rectangle{
                id:manStateList
                height:parent.height
                width:parent.width/3
                color:parent.color
                x:parent.width/3
                Rectangle{
                    height:parent.height/20
                    width:parent.width
                    color:titleBox.color
                    Text{
                        anchors.centerIn:parent
                        text:"Manuverability"
                    }
                }
                Rectangle{
                    height:parent.height-parent.height/20
                    width:parent.width
                    color:parent.color
                    y:parent.height/20
                ListView{
                    model: ListModel{
                        ListElement{name:"Running";value:1;box_color:"#00FF00"}
                        ListElement{name:"Reseting";value:2;box_color:"#FFFF00"}
                        ListElement{name:"Stopped";value:3;box_color:"#FF0000"}
                        
                    }
                    spacing:parent.height/50
                    width:parent.width
                    height:parent.height
                    delegate:Rectangle{
                        color:box_color
                        width:trackStateList.width
                        height:trackStateList.width
                        radius:height/5
                        Text{
                            anchors.centerIn:parent
                            text:name
                        }
                        MouseArea{
                            anchors.fill:parent
                            onClicked:dataModel.set_man_state(value)
                        }
                    }
                }
            }
        }
        Rectangle{
                id:durStateList
                height:parent.height
                width:parent.width/3
                color:parent.color
                x:parent.width*2/3
                Rectangle{
                    height:parent.height/20
                    width:parent.width
                    color:titleBox.color
                    Text{
                        anchors.centerIn:parent
                        text:"Durability"
                    }
                }
                Rectangle{
                    height:parent.height-parent.height/20
                    width:parent.width
                    color:parent.color
                    y:parent.height/20
                ListView{
                    model: ListModel{
                        ListElement{name:"Running";value:1;box_color:"#00FF00"}
                        ListElement{name:"Reseting";value:2;box_color:"#FFFF00"}
                        ListElement{name:"Stopped";value:3;box_color:"#FF0000"}
                        
                    }
                    spacing:parent.height/50
                    width:parent.width
                    height:parent.height
                    delegate:Rectangle{
                        color:box_color
                        width:trackStateList.width
                        height:trackStateList.width
                        radius:height/5
                        Text{
                            anchors.centerIn:parent
                            text:name
                        }
                        MouseArea{
                            anchors.fill:parent
                            onClicked:dataModel.set_dur_state(value)
                        }
                    }
                }
            }
        }
    }
    
}
